# -*- coding: utf-8 -*-
"""crypto volality risk analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bY0CrdtVnEt3wPXNYY8UygQYmr_k9ro3
"""



from google.colab import drive
drive.mount('/content/drive')

!pip install  streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.set_page_config(page_title="Crypto Volatility & Risk Analyzer")
# 
# st.title("📈 Crypto Volatility and Risk Analyzer")
# st.write("Analyze crypto volatility and risk level")
# 
# crypto_name = st.text_input("Enter Cryptocurrency Name")
# price_change = st.number_input("Enter Daily Price Change (%)", 0.0, 100.0)
# 
# if st.button("Analyze Risk"):
#     if price_change > 10:
#         risk = "High Risk"
#     elif price_change > 5:
#         risk = "Medium Risk"
#     else:
#         risk = "Low Risk"
# 
#     st.success(f"{crypto_name} Risk Level: {risk}")
#

!pip install pyngrok -q

from pyngrok import ngrok
import os
import time

# Kill any existing ngrok processes
os.system("killall ngrok")
ngrok.kill()

# Set ngrok authtoken directly using the provided token
ngrok.set_auth_token('39A8OmERwQezjQAUJ77HsMoVF2C_3AJzJQ15zNDmCv4rtDqnE')

# Kill any previously running streamlit processes to ensure the latest app.py is loaded
os.system("killall streamlit")

# Start streamlit in the background
os.system("streamlit run app.py &")

# Give Streamlit a moment to start
time.sleep(5)

# Create public URL, enabling pooling as suggested by ngrok error
public_url = ngrok.connect(8501, pooling_enabled=True)
print(public_url)